if|ESTRUCTURA SELECTIVA
else|ESTRUCTURA SELECTIVA
switch|ESTRUCTURA SELECTIVA
case|ESTRUCTURA SELECTIVA
for|ESTRUCTURA REPETITIVA
do|ESTRUCTURA REPETITIVA
while|ESTRUCTURA REPETITIVA
int|TIPO DE DATO
float|TIPO DE DATO
double|TIPO DE DATO
char|TIPO DE DATO
void|TIPO DE DATO
short|CALIFICADOR DE TIPO DE DATO
long|CALIFICADOR DE TIPO DE DATO
signed|CALIFICADOR DE TIPO DE DATO
unsigned|CALIFICADOR DE TIPO DE DATO
include|INSTRUCCION DEL PREPROCESADOR
define|INSTRUCCION DEL PREPROCESADOR
inline|INSTRUCCION DEL PREPROCESADOR
return|RETURN
main|MAIN
